language: node_js
node_js:
  - '10'

addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable --allow-unauthenticated

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
